### ISSUE TITLE
Many executable models refer to unaccessible data files

### ISSUE THREAD

**Issue by casella** [simulatino/OpenHPL#1]
Please check the OpenModelica [test report](https://libraries.openmodelica.org/branches/master/OpenHPL/OpenHPL.html) on the library. There are 21 models failing during the simulation stage because of errors of this kind
```
Not possible to open file "C:/Users/liubomyr/OneDrive/Documents/PhD/HydroCord/Servo_pos.txt":
No such file or directory
```
I would suggest to retrieve those files from Liubomyr's OneDrive account, put them under the `Resources` directory of the library, and access them via the `modelica://` URI and `loadFile` utility function.

**Comment by dietmarw** [comment]
@liubomyrv Do you still have those files and can either add them or send them to me?

**Comment by liubomyrv** [comment]
I will check it during the weekend and will let you know.

25. sep. 2019 08:30 skrev Dietmar Winkler <notifications@github.com>:

@liubomyrv<https://github.com/liubomyrv> Do you still have those files and can either add them or send them to me?
