### ISSUE TITLE
Are some executable models in the library broken?

### ISSUE THREAD

**Issue by casella** [simulatino/OpenHPL#2]
Please check the OpenModelica [old frontend test report](https://libraries.openmodelica.org/branches/master/OpenHPL/OpenHPL.html) on the library. There are many models  failing during the code generation phase. I understand the library was developed using OpenModelica/OMEdit, so those models should in principle work. 

Maybe they were broken during the library development and left like that because of lack of maintenance and proper CI monitoring. I would suggest to check them out thoroughly and either fix them or remove them from the library.

**Comment by dietmarw** [comment]
@casella all models under `test` should be ignored as they are not expected to be valid examples.

**Comment by dietmarw** [comment]
We are going to keep the test models in the library for now, regardless if working or not. If this is a problem for a third-party CI then they should exclude all models under `Tests`

**Comment by casella** [comment]
> We are going to keep the test models in the library for now, regardless if working or not. If this is a problem for a third-party CI then they should exclude all models under `Tests`

I guess we can't take this convention for granted in general. In fact, I find it rather odd that models in the Test library should actually not be tested 😄 

Anyway, I think in general it is perfectly legitimate to have models in a library that have the experiment annotation but shouldn't be part of CI testing for some reason (e.g., because they are supposed to fail by design, or because they are too cumbersome for routine testing).

One option is that we put a .testignore file somewhere with a list of models (or packages) that shouldn't be tested.

The other option is to embed this information in the library, by means of a vendor-specific annotation e.g. __OpenModelica.testIgnore(HPL.Tests)

@dietmarw, @adrpo, what do you think?

**Comment by dietmarw** [comment]
As I said we will not do any changes to that on our side.

**Comment by casella** [comment]
Not even if we make it a PR and it's one click away?

In exchange, you get CI for free

**Comment by dietmarw** [comment]
I guess I can afford a "click"
