### ISSUE TITLE
HPSimple_Francis_GridGen example fails to simulate

### ISSUE THREAD

**Issue by hellb0rg** [simulatino/OpenHPL#33]
Trying to run the example (HPSimple_Francis_GridGen) causes a crash.

After some digging around it seems to be due to the initial powerflow data in the order2 generator.
The values appear to be in Watts, but the fields take values that are in MW as illustrated in the image below.

Reducing these values to 16 and 11 respectively seems to solve the problem.

![image](https://user-images.githubusercontent.com/53197846/131958883-74e829f3-e3ef-4904-9c36-1942f661d3d0.png)

**Comment by dietmarw** [comment]
What version of OpenHPL are you using and which OpenIPSL?

**Comment by hellb0rg** [comment]
Closed the issue, unsure if you an remove it, but essentially the issue was that i was using an old version. 
Assumed i had gotten the latest version, but twas not so.
