### ISSUE TITLE
Wrong calculation of Area in Fitting

### ISSUE THREAD

**Issue by dietmarw** [simulatino/OpenHPL#8]
There seems to be some issues with the `Fitting` implementation.

One obvious one seems to be the wrong formula for area calculation in 
https://github.com/simulatino/OpenHPL/blob/6cbf8a63777fc5726d4c36689676cb4a86b52f0b/OpenHPL/Waterway/Fitting.mo#L20
where the "`^2`" is missing. Do you agree @liubomyrv ?
Also the output of the `phi` functions needs to be investigated as the function returns not the expected values.

**Comment by liubomyrv** [comment]
Agree with missing square of the diameter.
